export { default as Header } from "./header";
export { default as Post } from "./posts";
export { default as Home } from "./home";
export { default as Profile } from "./profile";
export { default as AddPost } from "./addPost";
export { default as Register } from "./register";
export { default as Login } from "./login";
export { default as SinglePost } from "./singlePost";
export { default as Message } from "./message"
